// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application_struct.proto

#ifndef PROTOBUF_application_5fstruct_2eproto__INCLUDED
#define PROTOBUF_application_5fstruct_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace application {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_application_5fstruct_2eproto();
void protobuf_AssignDesc_application_5fstruct_2eproto();
void protobuf_ShutdownFile_application_5fstruct_2eproto();

class T_APP_FIRST_TEST_RSP;
class T_APP_FIRST_TEST_REQ;

// ===================================================================

class T_APP_FIRST_TEST_RSP : public ::google::protobuf::Message {
 public:
  T_APP_FIRST_TEST_RSP();
  virtual ~T_APP_FIRST_TEST_RSP();

  T_APP_FIRST_TEST_RSP(const T_APP_FIRST_TEST_RSP& from);

  inline T_APP_FIRST_TEST_RSP& operator=(const T_APP_FIRST_TEST_RSP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const T_APP_FIRST_TEST_RSP& default_instance();

  void Swap(T_APP_FIRST_TEST_RSP* other);

  // implements Message ----------------------------------------------

  T_APP_FIRST_TEST_RSP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const T_APP_FIRST_TEST_RSP& from);
  void MergeFrom(const T_APP_FIRST_TEST_RSP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 u32Result = 1;
  inline bool has_u32result() const;
  inline void clear_u32result();
  static const int kU32ResultFieldNumber = 1;
  inline ::google::protobuf::uint32 u32result() const;
  inline void set_u32result(::google::protobuf::uint32 value);

  // required fixed32 u32Test = 2;
  inline bool has_u32test() const;
  inline void clear_u32test();
  static const int kU32TestFieldNumber = 2;
  inline ::google::protobuf::uint32 u32test() const;
  inline void set_u32test(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:application.T_APP_FIRST_TEST_RSP)
 private:
  inline void set_has_u32result();
  inline void clear_has_u32result();
  inline void set_has_u32test();
  inline void clear_has_u32test();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 u32result_;
  ::google::protobuf::uint32 u32test_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_application_5fstruct_2eproto();
  friend void protobuf_AssignDesc_application_5fstruct_2eproto();
  friend void protobuf_ShutdownFile_application_5fstruct_2eproto();

  void InitAsDefaultInstance();
  static T_APP_FIRST_TEST_RSP* default_instance_;
};
// -------------------------------------------------------------------

class T_APP_FIRST_TEST_REQ : public ::google::protobuf::Message {
 public:
  T_APP_FIRST_TEST_REQ();
  virtual ~T_APP_FIRST_TEST_REQ();

  T_APP_FIRST_TEST_REQ(const T_APP_FIRST_TEST_REQ& from);

  inline T_APP_FIRST_TEST_REQ& operator=(const T_APP_FIRST_TEST_REQ& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const T_APP_FIRST_TEST_REQ& default_instance();

  void Swap(T_APP_FIRST_TEST_REQ* other);

  // implements Message ----------------------------------------------

  T_APP_FIRST_TEST_REQ* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const T_APP_FIRST_TEST_REQ& from);
  void MergeFrom(const T_APP_FIRST_TEST_REQ& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 u32Result = 1;
  inline bool has_u32result() const;
  inline void clear_u32result();
  static const int kU32ResultFieldNumber = 1;
  inline ::google::protobuf::uint32 u32result() const;
  inline void set_u32result(::google::protobuf::uint32 value);

  // required fixed32 u32Test = 2;
  inline bool has_u32test() const;
  inline void clear_u32test();
  static const int kU32TestFieldNumber = 2;
  inline ::google::protobuf::uint32 u32test() const;
  inline void set_u32test(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:application.T_APP_FIRST_TEST_REQ)
 private:
  inline void set_has_u32result();
  inline void clear_has_u32result();
  inline void set_has_u32test();
  inline void clear_has_u32test();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 u32result_;
  ::google::protobuf::uint32 u32test_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_application_5fstruct_2eproto();
  friend void protobuf_AssignDesc_application_5fstruct_2eproto();
  friend void protobuf_ShutdownFile_application_5fstruct_2eproto();

  void InitAsDefaultInstance();
  static T_APP_FIRST_TEST_REQ* default_instance_;
};
// ===================================================================


// ===================================================================

// T_APP_FIRST_TEST_RSP

// required fixed32 u32Result = 1;
inline bool T_APP_FIRST_TEST_RSP::has_u32result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void T_APP_FIRST_TEST_RSP::set_has_u32result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void T_APP_FIRST_TEST_RSP::clear_has_u32result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void T_APP_FIRST_TEST_RSP::clear_u32result() {
  u32result_ = 0u;
  clear_has_u32result();
}
inline ::google::protobuf::uint32 T_APP_FIRST_TEST_RSP::u32result() const {
  return u32result_;
}
inline void T_APP_FIRST_TEST_RSP::set_u32result(::google::protobuf::uint32 value) {
  set_has_u32result();
  u32result_ = value;
}

// required fixed32 u32Test = 2;
inline bool T_APP_FIRST_TEST_RSP::has_u32test() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void T_APP_FIRST_TEST_RSP::set_has_u32test() {
  _has_bits_[0] |= 0x00000002u;
}
inline void T_APP_FIRST_TEST_RSP::clear_has_u32test() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void T_APP_FIRST_TEST_RSP::clear_u32test() {
  u32test_ = 0u;
  clear_has_u32test();
}
inline ::google::protobuf::uint32 T_APP_FIRST_TEST_RSP::u32test() const {
  return u32test_;
}
inline void T_APP_FIRST_TEST_RSP::set_u32test(::google::protobuf::uint32 value) {
  set_has_u32test();
  u32test_ = value;
}

// -------------------------------------------------------------------

// T_APP_FIRST_TEST_REQ

// required fixed32 u32Result = 1;
inline bool T_APP_FIRST_TEST_REQ::has_u32result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void T_APP_FIRST_TEST_REQ::set_has_u32result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void T_APP_FIRST_TEST_REQ::clear_has_u32result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void T_APP_FIRST_TEST_REQ::clear_u32result() {
  u32result_ = 0u;
  clear_has_u32result();
}
inline ::google::protobuf::uint32 T_APP_FIRST_TEST_REQ::u32result() const {
  return u32result_;
}
inline void T_APP_FIRST_TEST_REQ::set_u32result(::google::protobuf::uint32 value) {
  set_has_u32result();
  u32result_ = value;
}

// required fixed32 u32Test = 2;
inline bool T_APP_FIRST_TEST_REQ::has_u32test() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void T_APP_FIRST_TEST_REQ::set_has_u32test() {
  _has_bits_[0] |= 0x00000002u;
}
inline void T_APP_FIRST_TEST_REQ::clear_has_u32test() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void T_APP_FIRST_TEST_REQ::clear_u32test() {
  u32test_ = 0u;
  clear_has_u32test();
}
inline ::google::protobuf::uint32 T_APP_FIRST_TEST_REQ::u32test() const {
  return u32test_;
}
inline void T_APP_FIRST_TEST_REQ::set_u32test(::google::protobuf::uint32 value) {
  set_has_u32test();
  u32test_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace application

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_application_5fstruct_2eproto__INCLUDED
